#!/usr/bin/env python3
"""
RCSF System Initializer

Creates a new action-layer system with standard structure.
Handles GitHub repo creation and submodule setup.

Usage:
    python init_system.py <system-name> [--github-org <org>] [--no-github]

Examples:
    python init_system.py knowledge-network --github-org huya
    python init_system.py my-system --no-github
"""

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path


def run_cmd(cmd: str, check: bool = True) -> subprocess.CompletedProcess:
    """Run shell command and return result."""
    print(f"  $ {cmd}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if check and result.returncode != 0:
        print(f"  Error: {result.stderr}")
        sys.exit(1)
    return result


def create_github_repo(name: str, org: str, description: str) -> str:
    """Create private GitHub repository."""
    repo_full = f"{org}/ka-{name}" if org else f"ka-{name}"

    print(f"\n[1/5] Creating GitHub repository: {repo_full}")

    # Check if repo exists
    check = run_cmd(f'gh repo view {repo_full} --json name 2>/dev/null', check=False)
    if check.returncode == 0:
        print(f"  Repository {repo_full} already exists, skipping creation")
        return f"git@github.com:{repo_full}.git"

    # Create repo
    run_cmd(f'gh repo create {repo_full} --private --description "{description}"')

    return f"git@github.com:{repo_full}.git"


def add_submodule(vault_root: Path, system_name: str, repo_url: str) -> None:
    """Add repository as git submodule."""
    print(f"\n[2/5] Adding submodule to action/{system_name}")

    os.chdir(vault_root)

    # Check if submodule already exists
    submodule_path = vault_root / "action" / system_name
    if submodule_path.exists():
        print(f"  Directory action/{system_name} already exists, skipping")
        return

    run_cmd(f'git submodule add {repo_url} action/{system_name}')
    run_cmd('git submodule update --init --recursive')


def create_system_structure(system_path: Path, system_name: str, description: str) -> None:
    """Create standard system directory structure."""
    print(f"\n[3/5] Creating system structure")

    # Create directories
    dirs = ['skills', 'tools', 'workflows', 'hooks', 'config', '.claude']
    for d in dirs:
        (system_path / d).mkdir(parents=True, exist_ok=True)
        print(f"  Created: {d}/")

    # Create README.md
    readme_content = f"""# {system_name.replace('-', ' ').title()}

> {description}

## Overview

This system is part of the KA-Vault action layer, built using the RCSF architecture.

## Components

- `skills/` - Skill definitions (SKILL.md files)
- `tools/` - Python scripts for atomic operations
- `workflows/` - Workflow definitions
- `hooks/` - Event handlers
- `config/` - Configuration files

## Usage

```bash
# Example skill invocation
# ...
```

## Related

- [[action/RCSF/README.md]] - RCSF Meta-system
- [[cognition/agentic-software-paradigm/README.md]] - Agentic Software Paradigm

---

*Generated by RCSF on {datetime.now().strftime('%Y-%m-%d')}*
"""
    (system_path / 'README.md').write_text(readme_content, encoding='utf-8')
    print(f"  Created: README.md")

    # Create .claude/settings.json
    settings = {
        "projectRoot": ".",
        "skills": {
            "path": "skills"
        }
    }
    (system_path / '.claude' / 'settings.json').write_text(
        json.dumps(settings, indent=2), encoding='utf-8'
    )
    print(f"  Created: .claude/settings.json")


def register_system(vault_root: Path, system_name: str, description: str) -> None:
    """Register system in RCSF Registry."""
    print(f"\n[4/5] Registering system in RCSF Registry")

    registry_path = vault_root / 'action' / 'RCSF' / 'Registry' / 'systems.json'

    if not registry_path.exists():
        print(f"  Registry not found at {registry_path}, skipping")
        return

    registry = json.loads(registry_path.read_text(encoding='utf-8'))

    # Check if already registered
    for sys in registry.get('systems', []):
        if sys.get('name') == system_name:
            print(f"  System {system_name} already registered")
            return

    # Add new system
    registry['systems'].append({
        "name": system_name,
        "path": f"action/{system_name}",
        "created": datetime.now().strftime('%Y-%m-%d'),
        "status": "active",
        "description": description,
        "components": ["skills"]
    })
    registry['stats']['total_created'] = len(registry['systems'])
    registry['stats']['active'] = len([s for s in registry['systems'] if s.get('status') == 'active'])

    registry_path.write_text(json.dumps(registry, indent=2, ensure_ascii=False), encoding='utf-8')
    print(f"  Registered: {system_name}")


def commit_changes(vault_root: Path, system_name: str) -> None:
    """Commit the new system to git."""
    print(f"\n[5/5] Committing changes")

    os.chdir(vault_root)
    run_cmd(f'git add .gitmodules action/{system_name} action/RCSF/Registry/systems.json', check=False)
    run_cmd(f'git commit -m "Add {system_name} system"', check=False)


def main():
    parser = argparse.ArgumentParser(description='Initialize a new RCSF action-layer system')
    parser.add_argument('name', help='System name (lowercase, hyphen-separated)')
    parser.add_argument('--github-org', '-o', help='GitHub organization or username')
    parser.add_argument('--no-github', action='store_true', help='Skip GitHub repo creation')
    parser.add_argument('--description', '-d', default='', help='System description')
    parser.add_argument('--vault-root', '-r', help='Path to vault root')

    args = parser.parse_args()

    # Validate name
    system_name = args.name.lower().replace(' ', '-')
    if not system_name.replace('-', '').isalnum():
        print(f"Error: Invalid system name '{system_name}'. Use only letters, numbers, and hyphens.")
        sys.exit(1)

    # Determine vault root
    vault_root = Path(args.vault_root) if args.vault_root else Path.cwd()
    while vault_root != vault_root.parent:
        if (vault_root / 'action' / 'RCSF').exists():
            break
        vault_root = vault_root.parent
    else:
        print("Error: Could not find vault root (looking for action/RCSF)")
        sys.exit(1)

    description = args.description or f"Action-layer system for {system_name}"

    print(f"=== RCSF System Initializer ===")
    print(f"System: {system_name}")
    print(f"Vault:  {vault_root}")
    print(f"Desc:   {description}")

    system_path = vault_root / 'action' / system_name

    # Step 1: Create GitHub repo (optional)
    if not args.no_github:
        if not args.github_org:
            print("\nError: --github-org is required unless --no-github is specified")
            sys.exit(1)
        repo_url = create_github_repo(system_name, args.github_org, description)

        # Step 2: Add submodule
        add_submodule(vault_root, system_name, repo_url)
    else:
        print("\n[1-2/5] Skipping GitHub and submodule setup (--no-github)")
        system_path.mkdir(parents=True, exist_ok=True)

    # Step 3: Create structure
    create_system_structure(system_path, system_name, description)

    # Step 4: Register
    register_system(vault_root, system_name, description)

    # Step 5: Commit
    if not args.no_github:
        commit_changes(vault_root, system_name)

    print(f"\n=== Done! ===")
    print(f"System created at: action/{system_name}/")
    print(f"\nNext steps:")
    print(f"  1. cd action/{system_name}")
    print(f"  2. Create skills in skills/ directory")
    print(f"  3. Add tools in tools/ directory")


if __name__ == '__main__':
    main()
